DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(30) NOT NULL,       
  pw VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS scores CASCADE;
CREATE TABLE IF NOT EXISTS scores(
  score_id SERIAL PRIMARY KEY,     
  score INTEGER NOT NULL,   
  user_id INTEGER NOT NULL
);

